FootBundle\Entity\FootballPlayer:
    type: entity
    table: null
    repositoryClass: FootBundle\Repository\FootballPlayerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
            nullable: true
        size:
            type: string
            length: 255
        age:
            type: integer
        photo:
            type: string
            length: 255
    manyToOne:
        post:
            targetEntity: FootBundle\Entity\Post
    manyToMany:
        team:
            targetEntity: FootBundle\Entity\Team
            mappedBy: footballplayer

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
