FootBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: FootBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        position:
            type: string
            length: 255
        photo:
            type: string
            lenght: 255
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
