FootBundle\Entity\Team:
    type: entity
    table: null
    repositoryClass: FootBundle\Repository\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        city:
            type: string
            length: 255
        photo:
            type: string
            length: 255

    manyToMany:
        footballplayer:
            targetEntity: FootBundle\Entity\FootballPlayer

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]