footballplayer_index:
    path:     /
    defaults: { _controller: "FootBundle:FootballPlayer:index" }
    methods:  GET

footballplayer_show:
    path:     /{id}/show
    defaults: { _controller: "FootBundle:FootballPlayer:show" }
    methods:  GET

footballplayer_new:
    path:     /new
    defaults: { _controller: "FootBundle:FootballPlayer:new" }
    methods:  [GET, POST]

footballplayer_edit:
    path:     /{id}/edit
    defaults: { _controller: "FootBundle:FootballPlayer:edit" }
    methods:  [GET, POST]

footballplayer_delete:
    path:     /{id}/delete
    defaults: { _controller: "FootBundle:FootballPlayer:delete" }
    methods:  DELETE
